FROM registry.cn-hangzhou.aliyuncs.com/gerry_ai/deploy_nlp:v20240624_01

# 这里可以写很多docker的命令: https://www.runoob.com/docker/docker-dockerfile.html



RUN /mnt/miniconda3/bin/pip install flask -i http://mirrors.cloud.aliyuncs.com/pypi/simple/ --trusted-host mirrors.cloud.aliyuncs.com

